export const reportDummyTableData = [
    {
        Id: 1,
        DownloadType: 'Event',
        GroupEventId: 1,
        GroupEventName: 'Virtue',
        EventId: 100,
        EventName: 'Virtue Agustus',
        CompanyId: 102,
        CompanyName: 'Astra International',
        PositionId: 79,
        PositionName: 'Position Name',
        VacancyId: 200,
        VacancyCode: 'ABC AAAA CCC',
        AtsPhaseId: 1212,
        AtsPhaseName: 'All',
        ReportAnalyticsTypeId: 'FLKExcel',
        PeriodStart: null,
        PeriodEnd: null,
        ExportDate: '9/10/2021',
        ReportAnalyticsTypeName: 'Formulir Lamaran Kerja (.xlsx)',
        Status: 'Completed',
        Url: 'https://google.com/',
        PIC: 'PIC name',
        reExportCount: 10
    },
    {
        Id: 2,
        DownloadType: 'Event',
        GroupEventId: 1,
        GroupEventName: 'Virtue',
        EventId: 100,
        EventName: 'Event Name',
        CompanyId: 102,
        CompanyName: 'Company Name',
        PositionId: 79,
        PositionName: 'Position Name',
        VacancyId: 200,
        VacancyCode: 'ABCCCCBBBCCC',
        AtsPhaseId: 1212,
        AtsPhaseName: 'All',
        ReportAnalyticsTypeId: 'FLKPdf',
        PeriodStart: null,
        PeriodEnd: null,
        ExportDate: '9/10/2021',
        ReportAnalyticsTypeName: 'Formulir Lamaran Kerja (.pdf)',
        Status: 'Completed',
        Url: 'https://google.com/',
        PIC: 'PIC name',
        reExportCount: 10
    },
    {
        Id: 3,
        DownloadType: 'Period',
        GroupEventId: 3,
        GroupEventName: 'Virtue',
        EventId: 100,
        EventName: 'Virtue Agustus',
        CompanyId: 102,
        CompanyName: 'Astra International',
        PositionId: 79,
        PositionName: 'Position Name',
        VacancyId: 200,
        VacancyCode: 'ABC AAAA CCC',
        AtsPhaseId: 1212,
        AtsPhaseName: 'All',
        ReportAnalyticsTypeId: 'FLKExcel',
        PeriodStart: '01/01/2021',
        PeriodEnd: '01/02/2021',
        ExportDate: '9/10/2021',
        ReportAnalyticsTypeName: 'Formulir Lamaran Kerja (.xlsx)',
        Status: 'Completed',
        Url: 'https://google.com/',
        PIC: 'PIC name',
        reExportCount: 0
    },
    {
        Id: 4,
        DownloadType: 'Period',
        GroupEventId: 3,
        GroupEventName: 'Virtue',
        EventId: 100,
        EventName: 'Virtue Agustus',
        CompanyId: 102,
        CompanyName: 'Astra International',
        PositionId: 79,
        PositionName: 'Position Name',
        VacancyId: 200,
        VacancyCode: 'ABC AAAA CCC',
        AtsPhaseId: 1212,
        AtsPhaseName: 'All',
        ReportAnalyticsTypeId: 'FLKExcel',
        PeriodStart: '01/01/2021',
        PeriodEnd: '01/02/2021',
        ExportDate: '9/10/2021',
        ReportAnalyticsTypeName: 'Formulir Lamaran Kerja (.xlsx)',
        Status: 'Waiting',
        Url: 'https://google.com/',
        PIC: 'PIC name',
        reExportCount: 0
    },
    {
        Id: 5,
        DownloadType: 'Event',
        GroupEventId: 3,
        GroupEventName: 'Virtue',
        EventId: 100,
        EventName: 'Virtue Agustus',
        CompanyId: 102,
        CompanyName: 'Astra International',
        PositionId: 79,
        PositionName: 'Position Name',
        VacancyId: 200,
        VacancyCode: 'ABC AAAA CCC',
        AtsPhaseId: 1212,
        AtsPhaseName: 'All',
        ReportAnalyticsTypeId: 'FLKExcel',
        PeriodStart: null,
        PeriodEnd: null,
        ExportDate: '9/10/2021',
        ReportAnalyticsTypeName: 'Formulir Lamaran Kerja (.xlsx)',
        Status: 'Waiting',
        Url: 'https://google.com/',
        PIC: 'PIC name',
        reExportCount: 6
    }
]
